/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6;

import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author harsh
 */
public class four extends javax.swing.JFrame {

    /**
     * Creates new form four
     */
    public four() {
        initComponents();
    }
      public four(String para){
        initComponents();
       
        mID.setText(para);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        city = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cust = new javax.swing.JTable();
        title = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bill = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addnew = new javax.swing.JPanel();
        cn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        custid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bdate = new javax.swing.JTextField();
        discp = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        generate = new javax.swing.JButton();
        back = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        mID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setLayout(null);

        city.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        city.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(city);
        city.setBounds(190, 20, 180, 20);

        cust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer_ID", "Customer_Name", "Customer_EMail", "Contact_No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(cust);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 80, 510, 100);

        title.setText("Customer:");
        jPanel1.add(title);
        title.setBounds(30, 60, 70, 16);

        bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Bill_No", "Customer_ID", "Bill_Date", "Price", "Discount (%)", "Net_Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bill.setOpaque(false);
        jScrollPane2.setViewportView(bill);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 390, 510, 110);

        jButton1.setText("Sign Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(230, 510, 90, 20);

        jLabel2.setText("Bill:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 370, 41, 16);

        addnew.setBorder(javax.swing.BorderFactory.createTitledBorder("Add new customer"));
        addnew.setOpaque(false);
        addnew.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        addnew.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 90, -1));

        jLabel3.setText("Customer Name");
        addnew.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        addnew.add(cemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 90, -1));

        jLabel4.setText("Customer EMail");
        addnew.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, -1));
        addnew.add(cno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 90, -1));

        jLabel5.setText("Contact No");
        addnew.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, -1));

        add.setText("Add");
        add.setFocusPainted(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        addnew.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jPanel1.add(addnew);
        addnew.setBounds(30, 190, 260, 170);

        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next);
        next.setBounds(429, 510, 110, 25);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bill"));
        jPanel2.setToolTipText("");
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Customer ID");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, -1));
        jPanel2.add(custid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 90, -1));

        jLabel1.setText("Billing date");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel6.setText("Discount %");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        jPanel2.add(bdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 90, -1));
        jPanel2.add(discp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 90, -1));

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel2.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 90, -1));

        jLabel8.setText("Price");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 60, -1));

        generate.setText("Generate Bill");
        generate.setFocusPainted(false);
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });
        jPanel2.add(generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(300, 190, 240, 190);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(30, 510, 110, 25);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication6/emp_image.png"))); // NOI18N
        image.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                imageComponentShown(evt);
            }
        });
        jPanel1.add(image);
        image.setBounds(0, 0, 560, 550);

        mID.setOpaque(true);
        jPanel1.add(mID);
        mID.setBounds(110, 520, 80, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
   
        String b=cn.getText();
        String c=cemail.getText();
        String d=cno.getText();
        

        String url="jdbc:mysql://localhost:3306/project?useSSL=true";
        String user="root";
        String pass="harsh";

        try{

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection(url,user,pass);

           

            String sql5 = "insert into customer(customer_email,contact_no,customer_name) values(?,?,?);";
            PreparedStatement pst5 = conn.prepareStatement(sql5);
            pst5.setString(1,c);
            pst5.setString(2,d);
            pst5.setString(3,b);
            pst5.executeUpdate();
            
  


            JOptionPane.showMessageDialog(null,"New customer details added successfuly!");

            sleep(5);
            
             String sql="select branch_id from branch where manager_id=?";
             PreparedStatement pst=conn.prepareStatement(sql);
             pst.setString(1, mID.getText());
             ResultSet rs=pst.executeQuery();
             rs.next();
             int j=rs.getInt("Branch_id");
            
          
             String sql2="select c.customer_id,c.customer_name,c.customer_email,c.contact_no from customer c inner join bill b on c.customer_id=b.customer_id where branch_id=?;";
             PreparedStatement pst1=conn.prepareStatement(sql2);
             pst1.setInt(1, j);
             ResultSet rs1=pst1.executeQuery();
             
             
             
             DefaultTableModel tm=(DefaultTableModel)cust.getModel();
             tm.setRowCount(0);
              while(rs1.next())
                        {
                           Object o[]={rs1.getInt("Customer_ID"),rs1.getString("Customer_Name"),rs1.getString("Customer_EMail"),rs1.getString("Contact_No")};
                              tm.addRow(o);
                        }
            
            
     
             
            conn.close();
        }catch(Exception f){System.out.println(f);}

  
        cn.setText("");
        cemail.setText("");
        cno.setText("");
        
    }//GEN-LAST:event_addActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
           String a=(mID.getText());
             
            
    
            
                dispose();
                new five(a).setVisible(true);
    }//GEN-LAST:event_nextActionPerformed

    private void imageComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imageComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_imageComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
       String url="jdbc:mysql://localhost:3306/project?useSSL=true";
       String user="root";
       String pass="harsh";
       
               try{

             Class.forName("com.mysql.cj.jdbc.Driver");
             Connection conn=DriverManager.getConnection(url,user,pass);
            
            
             //setting table values 
             String sql="select branch_id from branch where manager_id=?";
             PreparedStatement pst=conn.prepareStatement(sql);
             pst.setString(1, mID.getText());
             ResultSet rs=pst.executeQuery();
             rs.next();
             int b=rs.getInt("Branch_id");
            
          
             String sql2="select c.customer_id,c.customer_name,c.customer_email,c.contact_no from customer c inner join bill b on c.customer_id=b.customer_id where branch_id=?;";
             PreparedStatement pst1=conn.prepareStatement(sql2);
             pst1.setInt(1, b);
             ResultSet rs1=pst1.executeQuery();
             
             
             
             DefaultTableModel tm=(DefaultTableModel)cust.getModel();
             tm.setRowCount(0);
              while(rs1.next())
                        {
                           Object o[]={rs1.getInt("Customer_ID"),rs1.getString("Customer_Name"),rs1.getString("Customer_EMail"),rs1.getString("Contact_No")};
                              tm.addRow(o);
                        }
            
              
             String sql4="Select bill_no,customer_id,bdate,price,discount_percent,net_Price from bill where branch_id=?;";
             PreparedStatement pst4=conn.prepareStatement(sql4);
             pst4.setInt(1, b);
             ResultSet rs4=pst4.executeQuery();
             
             DefaultTableModel tm1=(DefaultTableModel)bill.getModel();
             tm1.setRowCount(0);
              while(rs4.next())
                        {
                           Object o[]={rs4.getInt("Bill_No"),rs4.getInt("Customer_ID"),rs4.getString("bdate"),rs4.getInt("Price"),rs4.getInt("Discount_percent"),rs4.getInt("Net_Price")};
                              tm1.addRow(o);
                        }
              
              
               String sql3 = "Select city from branch where manager_id=?";
             PreparedStatement pst2 = conn.prepareStatement(sql3);
             pst2.setString(1, mID.getText());
             ResultSet rs3 = pst2.executeQuery();
            
             rs3.next();
             String op=rs3.getString(1);
            
             
             city.setText(op+" Branch");
             conn.close();
      }catch(Exception e){System.out.println(e);}
        
        
    }//GEN-LAST:event_formComponentShown

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        // TODO add your handling code here:
        int a=Integer.parseInt(custid.getText());
        String b=bdate.getText();
        int c=Integer.parseInt(price.getText());
        int d=Integer.parseInt(discp.getText());
        int e=((100-d)*c)/100;
        
        
        
     
        

        String url="jdbc:mysql://localhost:3306/project?useSSL=true";
        String user="root";
        String pass="harsh";

        try{

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection(url,user,pass);

             String sql="select branch_id from branch where manager_id=?";
             PreparedStatement pst=conn.prepareStatement(sql);
             pst.setString(1, mID.getText());
             ResultSet rs=pst.executeQuery();
             rs.next();
             int j=rs.getInt("Branch_id");

             
             
             
            String sql5 = "insert into bill(branch_id,customer_id,bdate,price,discount_percent,net_price) values(?,?,?,?,?,?);";
            PreparedStatement pst5 = conn.prepareStatement(sql5);
            pst5.setInt(1,j);
            pst5.setInt(2,a);
            pst5.setString(3,b);
            pst5.setInt(4,c);
            pst5.setInt(5,d); 
            pst5.setInt(6,e);           
            pst5.executeUpdate();
            
 
            JOptionPane.showMessageDialog(null,"Bill generated successfully!");

            sleep(5);
            
                   
          
            String sql4="Select bill_no,customer_id,bdate,price,discount_percent,net_Price from bill where branch_id=?;";
             PreparedStatement pst4=conn.prepareStatement(sql4);
             pst4.setInt(1, j);
             ResultSet rs4=pst4.executeQuery();
             
             DefaultTableModel tm1=(DefaultTableModel)bill.getModel();
             tm1.setRowCount(0);
              while(rs4.next())
                        {
                           Object o[]={rs4.getInt("Bill_No"),rs4.getInt("Customer_ID"),rs4.getString("bdate"),rs4.getInt("Price"),rs4.getInt("Discount_percent"),rs4.getInt("Net_Price")};
                              tm1.addRow(o);
                        }
              
             String sql2="select c.customer_id,c.customer_name,c.customer_email,c.contact_no from customer c inner join bill b on c.customer_id=b.customer_id where branch_id=?;";
             PreparedStatement pst1=conn.prepareStatement(sql2);
             pst1.setInt(1, j);
             ResultSet rs1=pst1.executeQuery();
             
             
             
             DefaultTableModel tm=(DefaultTableModel)cust.getModel();
             tm.setRowCount(0);
              while(rs1.next())
                        {
                           Object o[]={rs1.getInt("Customer_ID"),rs1.getString("Customer_Name"),rs1.getString("Customer_EMail"),rs1.getString("Contact_No")};
                              tm.addRow(o);
                        }
            
            
             
            conn.close();
        }catch(Exception f){System.out.println(f);}

  
        custid.setText("");
        bdate.setText("");
        price.setText("");
        discp.setText("");
        
        
        
    }//GEN-LAST:event_generateActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         String a=(mID.getText());
             
            
    
            
                dispose();
                new six(a).setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            JOptionPane.showMessageDialog(null, "You have been successfully signed out!");
        dispose();
        new one().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(four.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(four.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(four.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(four.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new four().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JPanel addnew;
    private javax.swing.JButton back;
    private javax.swing.JTextField bdate;
    private javax.swing.JTable bill;
    private javax.swing.JTextField cemail;
    private javax.swing.JLabel city;
    private javax.swing.JTextField cn;
    private javax.swing.JTextField cno;
    private javax.swing.JTable cust;
    private javax.swing.JTextField custid;
    private javax.swing.JTextField discp;
    private javax.swing.JButton generate;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mID;
    private javax.swing.JButton next;
    private javax.swing.JTextField price;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
