/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication6;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harsh
 */
public class six extends javax.swing.JFrame {

    /** Creates new form six */
    public six() {
        initComponents();
        search.setAutoCreateRowSorter(true);
    }
public six(String para){
        initComponents();
       
        mID.setText(para);
        
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        city = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        search = new javax.swing.JTable();
        prod = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        prod1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        next = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        mID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search & Sort");

        jPanel1.setLayout(null);

        city.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        city.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(city);
        city.setBounds(190, 20, 180, 20);

        exit.setText("Sign Out");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(210, 500, 110, 25);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(20, 500, 70, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Products"));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Search by Product Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, -1));

        search.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Branch ID", "City", "Price", "Stock Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        search.setToolTipText("Click on column headings to arrange them in ascending or descending order");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        search.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                searchComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(search);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 150));

        prod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Philips Kettle", "Trimmer", "Philips Ironbox", "Hair Straightner", "Mountain Dew", "Appy Fizz", "Mirinda ", "Pepsi", "Pringles Original ", "Lays Magic Masala", "Doritos Cheese   ", "Bingo Mad Angles  ", "Nykaa Lipbalm     ", "Himalaya Soap     ", "VLCC Facewash     ", "Loreal Shampoo    ", "Nataraj Eraser    ", "Camlin Ruler      ", "Dairy Milk Silk   ", "Five Star         ", "Milky Bar         ", "Chart Paper       ", "Perk              ", "Nataraj Pencil" }));
        prod.setSelectedItem(null);
        prod.setToolTipText("");
        prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodActionPerformed(evt);
            }
        });
        jPanel2.add(prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 140, -1));

        jLabel2.setText("or");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel3.setText("Searrch by Product ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        prod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod1ActionPerformed(evt);
            }
        });
        jPanel2.add(prod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 140, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 90, 510, 340);

        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next);
        next.setBounds(430, 500, 110, 25);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication6/emp_image.png"))); // NOI18N
        image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageMouseClicked(evt);
            }
        });
        image.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                imageComponentShown(evt);
            }
        });
        jPanel1.add(image);
        image.setBounds(0, 0, 560, 550);

        mID.setOpaque(true);
        jPanel1.add(mID);
        mID.setBounds(110, 520, 80, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You have been successfully signed out!");
        dispose();
        new one().setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        String a=(mID.getText());

        dispose();
        new three(a).setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void imageComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imageComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_imageComponentShown

    private void prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodActionPerformed
        // TODO add your handling code here:
        search.setAutoCreateRowSorter(true);
               String url="jdbc:mysql://localhost:3306/project?useSSL=true";
       String user="root";
       String pass="harsh";
       
               try{

             Class.forName("com.mysql.cj.jdbc.Driver");
             Connection conn=DriverManager.getConnection(url,user,pass);
            
            
             //setting table values 
           
            
          
             String sql2="select s.branch_id,b.city,p.price,s.stock_quantity from ((stock s inner join product p on p.product_id=s.product_id) inner join branch b on b.branch_id=s.branch_id) where p.product_name=?";
             PreparedStatement pst1=conn.prepareStatement(sql2);
             String s=(String) prod.getSelectedItem();
             pst1.setString(1,s);
             ResultSet rs1=pst1.executeQuery();
             
             
             
             DefaultTableModel tm=(DefaultTableModel)search.getModel();
             tm.setRowCount(0);
              while(rs1.next())
                        {
                           Object o[]={rs1.getInt("branch_id"),rs1.getString("city"),rs1.getInt("price"),rs1.getInt("stock_quantity")};
                              tm.addRow(o);
                        }
            
           
              
             String sql3 = "Select city from branch where manager_id=?";
             PreparedStatement pst2 = conn.prepareStatement(sql3);
             pst2.setString(1, mID.getText());
             ResultSet rs4 = pst2.executeQuery();
            
             rs4.next();
             String op=rs4.getString(1);
            
             
             city.setText(op+" Branch");
             conn.close();
      }catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_prodActionPerformed

    private void prod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prod1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        search.setAutoCreateRowSorter(true);
       String url="jdbc:mysql://localhost:3306/project?useSSL=true";
       String user="root";
       String pass="harsh";
       
               try{

             Class.forName("com.mysql.cj.jdbc.Driver");
             Connection conn=DriverManager.getConnection(url,user,pass);
            
            
             //setting table values 
           
            
          
             String sql2="select s.branch_id,b.city,p.price,s.stock_quantity from ((stock s inner join product p on p.product_id=s.product_id) inner join branch b on b.branch_id=s.branch_id) where p.product_ID=?";
             PreparedStatement pst1=conn.prepareStatement(sql2);
            // int s=Integer.parseInt(prod1.getSelectedText());
             pst1.setInt(1,Integer.parseInt(prod1.getText()));
             ResultSet rs1=pst1.executeQuery();
             
             
             
             DefaultTableModel tm=(DefaultTableModel)search.getModel();
             tm.setRowCount(0);
              while(rs1.next())
                        {
                           Object o[]={rs1.getInt("branch_id"),rs1.getString("city"),rs1.getInt("price"),rs1.getInt("stock_quantity")};
                              tm.addRow(o);
                        }
            
           
              
             String sql3 = "Select city from branch where manager_id=?";
             PreparedStatement pst2 = conn.prepareStatement(sql3);
             pst2.setString(1, mID.getText());
             ResultSet rs4 = pst2.executeQuery();
            
             rs4.next();
             String op=rs4.getString(1);
            
             
             city.setText(op+" Branch");
             conn.close();
      }catch(Exception e){System.out.println(e);}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        String a=(mID.getText());

        dispose();
        new four(a).setVisible(true);
    }//GEN-LAST:event_nextActionPerformed

    private void searchComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_searchComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchComponentShown

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_searchMouseClicked

    private void imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_imageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(six.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(six.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(six.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(six.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new six().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel city;
    private javax.swing.JButton exit;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mID;
    private javax.swing.JButton next;
    private javax.swing.JComboBox<String> prod;
    private javax.swing.JTextField prod1;
    private javax.swing.JTable search;
    // End of variables declaration//GEN-END:variables

}
