/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6;

import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author harsh
 */
public class three extends javax.swing.JFrame {

    /**
     * Creates new form three
     */
    public three() {
        initComponents();
    }
     public three(String para){
        initComponents();
       
        mID.setText(para);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        city = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        product = new javax.swing.JTable();
        title = new javax.swing.JLabel();
        addnew = new javax.swing.JPanel();
        pid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pdesc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        deldata = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        delID = new javax.swing.JTextField();
        updatedata = new javax.swing.JPanel();
        updname = new javax.swing.JRadioButton();
        updprice = new javax.swing.JRadioButton();
        upddesc = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        newval = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        pro = new javax.swing.JTextField();
        updstock = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        next = new javax.swing.JButton();
        back = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        mID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Products");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setLayout(null);

        city.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        city.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(city);
        city.setBounds(190, 20, 180, 20);

        product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product_ID", "Product_Name", "Product_Desc", "Price", "Stock Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        product.setOpaque(false);
        jScrollPane1.setViewportView(product);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 80, 510, 100);

        title.setText("Products:");
        jPanel1.add(title);
        title.setBounds(30, 60, 70, 16);

        addnew.setBorder(javax.swing.BorderFactory.createTitledBorder("Add new product"));
        addnew.setOpaque(false);
        addnew.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        addnew.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 43, 90, -1));

        jLabel2.setText("Product_ID");
        addnew.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 49, 70, -1));
        addnew.add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 72, 90, -1));

        jLabel3.setText("Product_Name");
        addnew.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 78, -1, -1));
        addnew.add(pdesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 90, -1));

        jLabel4.setText("Product_Desc");
        addnew.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, -1));
        addnew.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 90, -1));

        jLabel5.setText("Price");
        addnew.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 60, -1));
        addnew.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 90, -1));

        jLabel6.setText("Stock");
        addnew.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, -1));

        add.setText("Add");
        add.setFocusPainted(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        addnew.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 265, -1, -1));

        jPanel1.add(addnew);
        addnew.setBounds(290, 190, 250, 310);

        deldata.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete product"));
        deldata.setOpaque(false);

        jLabel1.setText("Enter Product_ID");

        delete.setText("Delete");
        delete.setFocusPainted(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deldataLayout = new javax.swing.GroupLayout(deldata);
        deldata.setLayout(deldataLayout);
        deldataLayout.setHorizontalGroup(
            deldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deldataLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(deldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete)
                    .addGroup(deldataLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(delID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deldataLayout.setVerticalGroup(
            deldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deldataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(delID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(deldata);
        deldata.setBounds(20, 390, 260, 110);

        updatedata.setBorder(javax.swing.BorderFactory.createTitledBorder("Update data"));
        updatedata.setToolTipText("");
        updatedata.setOpaque(false);
        updatedata.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(updname);
        updname.setText("Product_Name");
        updname.setOpaque(false);
        updatedata.add(updname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        buttonGroup1.add(updprice);
        updprice.setText("Price");
        updprice.setOpaque(false);
        updatedata.add(updprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 84, -1));

        buttonGroup1.add(upddesc);
        upddesc.setText("Product_Desc");
        upddesc.setOpaque(false);
        updatedata.add(upddesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel7.setText("New Value");
        updatedata.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 107, -1, 31));
        updatedata.add(newval, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 107, 135, -1));

        update.setText("Update");
        update.setFocusPainted(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        updatedata.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 145, -1, -1));

        jLabel8.setText("Enter Product_ID");
        updatedata.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 83, -1, -1));
        updatedata.add(pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 80, 135, -1));

        buttonGroup1.add(updstock);
        updstock.setText("Stock Quantity");
        updstock.setOpaque(false);
        updatedata.add(updstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jPanel1.add(updatedata);
        updatedata.setBounds(20, 190, 260, 190);

        jButton1.setText("Sign Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 510, 90, 25);

        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next);
        next.setBounds(429, 510, 110, 25);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(30, 510, 59, 25);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication6/emp_image.png"))); // NOI18N
        image.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                imageComponentShown(evt);
            }
        });
        jPanel1.add(image);
        image.setBounds(0, 0, 560, 550);

        mID.setOpaque(true);
        jPanel1.add(mID);
        mID.setBounds(110, 520, 80, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        int a=Integer.parseInt(pid.getText());
        String b=pn.getText();
        String c=pdesc.getText();
        int d=Integer.parseInt(price.getText());
        int e=Integer.parseInt(stock.getText());

        String url="jdbc:mysql://localhost:3306/project?useSSL=true";
        String user="root";
        String pass="harsh";

        try{

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection(url,user,pass);
            
            
             String sql3="select branch_id from branch where manager_id=?";
             PreparedStatement pst2=conn.prepareStatement(sql3);
             pst2.setString(1, mID.getText());
             ResultSet rs2=pst2.executeQuery();
             rs2.next();
             int x=rs2.getInt("Branch_id");
             
            String sql = "insert into product values(?,?,?,?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1,a);
            pst.setString(2,b);
            pst.setString(3,c);
            pst.setInt(4,d);
            pst.executeUpdate();
            
            String sql4 = "insert into stock values(?,?,?)";
            PreparedStatement pst3 = conn.prepareStatement(sql4);
            pst3.setInt(1,x);
            pst3.setInt(2,a);
            pst3.setInt(3,e);
            pst3.executeUpdate();

            JOptionPane.showMessageDialog(null,"New product details added successfuly!");

            sleep(5);

      
            
            
          
             String sql2="select p.product_id,p.product_name,p.product_desc,p.price,s.stock_quantity from stock s inner join product p on p.product_id=s.product_id where s.branch_id=?";
             PreparedStatement pst1=conn.prepareStatement(sql2);
             pst1.setInt(1, x);
             ResultSet rs1=pst1.executeQuery();
             
             
             
             DefaultTableModel tm=(DefaultTableModel)product.getModel();
             tm.setRowCount(0);
              while(rs1.next())
                        {
                           Object o[]={rs1.getInt("product_id"),rs1.getString("product_name"),rs1.getString("product_desc"),rs1.getInt("price"),rs1.getInt("stock_Quantity")};
                              tm.addRow(o);
                        }
            

            conn.close();
        }catch(Exception f){System.out.println(f);}

        pid.setText("");
        pn.setText("");
        pdesc.setText("");
        price.setText("");
        stock.setText("");

    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:

        String url="jdbc:mysql://localhost:3306/project?useSSL=true";
        String user="root";
        String pass="harsh";

        try{

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection(url,user,pass);
            //deleting data
            String sql3="select branch_id from branch where manager_id=?";
             PreparedStatement pst2=conn.prepareStatement(sql3);
             pst2.setString(1, mID.getText());
             ResultSet rs2=pst2.executeQuery();
             rs2.next();
             int x=rs2.getInt("Branch_id");
            
            
            
            String sql = "delete p,s from product p inner join stock s on p.product_id=s.product_id where p.product_id=? and s.branch_id=?;";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(delID.getText()));
            pst.setInt(2,x);
            pst.executeUpdate();

            int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete all data related to this product?",null, JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION)
            {
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Product details deleted successfully!");
            }

            //setting table values
              String sql2="select p.product_id,p.product_name,p.product_desc,p.price,s.stock_quantity from stock s inner join product p on p.product_id=s.product_id where s.branch_id=?";
             PreparedStatement pst1=conn.prepareStatement(sql2);
             pst1.setInt(1, x);
             ResultSet rs1=pst1.executeQuery();
             
             
             
             DefaultTableModel tm=(DefaultTableModel)product.getModel();
             tm.setRowCount(0);
              while(rs1.next())
                        {
                           Object o[]={rs1.getInt("product_id"),rs1.getString("product_name"),rs1.getString("product_desc"),rs1.getInt("price"),rs1.getInt("stock_Quantity")};
                              tm.addRow(o);
                        }

            conn.close();
            delID.setText("");
        }catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String url="jdbc:mysql://localhost:3306/project?useSSL=true";
        String user="root";
        String pass="harsh";

        int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to update data?",null, JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION)
        {

            try{

                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn=DriverManager.getConnection(url,user,pass);
                //updating data
             String sql3="select branch_id from branch where manager_id=?";
             PreparedStatement pst2=conn.prepareStatement(sql3);
             pst2.setString(1, mID.getText());
             ResultSet rs2=pst2.executeQuery();
             rs2.next();
             int x=rs2.getInt("Branch_id");
             
                if(updname.isSelected())
                {
                    int a=Integer.parseInt(pro.getText());
                    String b=newval.getText();
                    String sql = "update product p inner join stock s on p.product_id=s.product_id set p.product_name=? where p.product_id=? and  s.branch_id=?;";
                    PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setString(1, b);
                    pst.setInt(2, a);
                    pst.setInt(3, x);
                    pst.executeUpdate();
                }
                else if(updprice.isSelected())
                {
                    int a=Integer.parseInt(pro.getText());
                    int b=Integer.parseInt(newval.getText());
                    String sql = "update product p inner join stock s on p.product_id=s.product_id set p.price=? where p.product_id=? and  s.branch_id=?;";
                    PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setInt(1, b);
                    pst.setInt(2, a);
                    pst.setInt(3, x);
                    pst.executeUpdate();
                }
                else if(upddesc.isSelected())
                {
                    int a=Integer.parseInt(pro.getText());
                    String b=newval.getText();
                    String sql = "update product p inner join stock s on p.product_id=s.product_id set p.product_desc=? where p.product_id=? and  s.branch_id=?;";
                    PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setString(1, b);
                    pst.setInt(2, a);
                    pst.setInt(3, x);
                    pst.executeUpdate();
                }
                else if(updstock.isSelected())
                {
                    int a=Integer.parseInt(pro.getText());
                    int b=Integer.parseInt(newval.getText());
                    String sql = "update stock set stock_quantity=? where product_id=? and  branch_id=?;";
                    PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setInt(1, b);
                    pst.setInt(2, a);
                    pst.setInt(3, x);
                    pst.executeUpdate();
                }

                JOptionPane.showMessageDialog(null,"Product detail updated successfully!");

                //setting table values
                String sql2="select p.product_id,p.product_name,p.product_desc,p.price,s.stock_quantity from stock s inner join product p on p.product_id=s.product_id where s.branch_id=?";
             PreparedStatement pst1=conn.prepareStatement(sql2);
             pst1.setInt(1, x);
             ResultSet rs1=pst1.executeQuery();
             
             
             
             DefaultTableModel tm=(DefaultTableModel)product.getModel();
             tm.setRowCount(0);
              while(rs1.next())
                        {
                           Object o[]={rs1.getInt("product_id"),rs1.getString("product_name"),rs1.getString("product_desc"),rs1.getInt("price"),rs1.getInt("stock_Quantity")};
                              tm.addRow(o);
                        }

                pro.setText("");
                newval.setText("");
                buttonGroup1.clearSelection();
          
                conn.close();
            }catch(Exception e){System.out.println(e);}
        }
    }//GEN-LAST:event_updateActionPerformed

    private void imageComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imageComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_imageComponentShown

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
         String a=(mID.getText());
             
            
    
            
                dispose();
                new six(a).setVisible(true);
    }//GEN-LAST:event_nextActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
          
       String url="jdbc:mysql://localhost:3306/project?useSSL=true";
       String user="root";
       String pass="harsh";
       
               try{

             Class.forName("com.mysql.cj.jdbc.Driver");
             Connection conn=DriverManager.getConnection(url,user,pass);
            
            
             //setting table values 
             String sql="select branch_id from branch where manager_id=?";
             PreparedStatement pst=conn.prepareStatement(sql);
             pst.setString(1, mID.getText());
             ResultSet rs=pst.executeQuery();
             rs.next();
             int b=rs.getInt("Branch_id");
            
          
             String sql2="select p.product_id,p.product_name,p.product_desc,p.price,s.stock_quantity from stock s inner join product p on p.product_id=s.product_id where s.branch_id=?";
             PreparedStatement pst1=conn.prepareStatement(sql2);
             pst1.setInt(1, b);
             ResultSet rs1=pst1.executeQuery();
             
             
             
             DefaultTableModel tm=(DefaultTableModel)product.getModel();
             tm.setRowCount(0);
              while(rs1.next())
                        {
                           Object o[]={rs1.getInt("product_id"),rs1.getString("product_name"),rs1.getString("product_desc"),rs1.getInt("price"),rs1.getInt("stock_Quantity")};
                              tm.addRow(o);
                        }
            
              
              
               String sql3 = "Select city from branch where manager_id=?";
             PreparedStatement pst2 = conn.prepareStatement(sql3);
             pst2.setString(1, mID.getText());
             ResultSet rs3 = pst2.executeQuery();
            
             rs3.next();
             String op=rs3.getString(1);
            
             
             city.setText(op+" Branch");
             conn.close();
      }catch(Exception e){System.out.println(e);}
        
    }//GEN-LAST:event_formComponentShown

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         String a=(mID.getText());
             
            
    
            
                dispose();
                new two(a).setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            JOptionPane.showMessageDialog(null, "You have been successfully signed out!");
        dispose();
        new one().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(three.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(three.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(three.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(three.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new three().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JPanel addnew;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel city;
    private javax.swing.JTextField delID;
    private javax.swing.JPanel deldata;
    private javax.swing.JButton delete;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mID;
    private javax.swing.JTextField newval;
    private javax.swing.JButton next;
    private javax.swing.JTextField pdesc;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pn;
    private javax.swing.JTextField price;
    private javax.swing.JTextField pro;
    private javax.swing.JTable product;
    private javax.swing.JTextField stock;
    private javax.swing.JLabel title;
    private javax.swing.JButton update;
    private javax.swing.JPanel updatedata;
    private javax.swing.JRadioButton upddesc;
    private javax.swing.JRadioButton updname;
    private javax.swing.JRadioButton updprice;
    private javax.swing.JRadioButton updstock;
    // End of variables declaration//GEN-END:variables
}
