/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6;


import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harsh
 */
public class two extends javax.swing.JFrame {

    /**
     * Creates new form two
     */
    public two() {
        initComponents();
    }

    public two(String para){
        initComponents();
        mID.setText(para);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        city = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employee = new javax.swing.JTable();
        title = new javax.swing.JLabel();
        addnew = new javax.swing.JPanel();
        eid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        en = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        esal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        deldata = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        delID = new javax.swing.JTextField();
        updatedata = new javax.swing.JPanel();
        updeid = new javax.swing.JRadioButton();
        updname = new javax.swing.JRadioButton();
        updsal = new javax.swing.JRadioButton();
        updjdate = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        newval = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        emp = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        mID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setLayout(null);

        city.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        city.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(city);
        city.setBounds(190, 20, 180, 20);

        employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Emp_ID", "EName", "ESalary", "Join_Date", "Branch_ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employee.setOpaque(false);
        jScrollPane1.setViewportView(employee);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 80, 510, 100);

        title.setText("Employees:");
        jPanel1.add(title);
        title.setBounds(30, 60, 70, 16);

        addnew.setBorder(javax.swing.BorderFactory.createTitledBorder("Add new Employee"));
        addnew.setOpaque(false);
        addnew.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        addnew.add(eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 43, 90, -1));

        jLabel2.setText("Emp_ID");
        addnew.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 49, 70, -1));
        addnew.add(en, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 72, 90, -1));

        jLabel3.setText("EName");
        addnew.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 78, -1, -1));
        addnew.add(esal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 90, -1));

        jLabel4.setText("ESalary");
        addnew.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 60, -1));
        addnew.add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 90, -1));

        jLabel5.setText("Join_Date");
        addnew.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 60, -1));
        addnew.add(bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 90, -1));

        jLabel6.setText("Branch_ID");
        addnew.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, -1));

        add.setText("Add");
        add.setFocusPainted(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        addnew.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 265, -1, -1));

        jPanel1.add(addnew);
        addnew.setBounds(290, 190, 250, 310);

        jButton1.setText("Sign Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 510, 100, 25);

        deldata.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete employee"));
        deldata.setOpaque(false);

        jLabel1.setText("Enter Emp_ID");

        delete.setText("Delete");
        delete.setFocusPainted(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deldataLayout = new javax.swing.GroupLayout(deldata);
        deldata.setLayout(deldataLayout);
        deldataLayout.setHorizontalGroup(
            deldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deldataLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(deldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete)
                    .addGroup(deldataLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delID, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                .addContainerGap())
        );
        deldataLayout.setVerticalGroup(
            deldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deldataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deldataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(delID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(deldata);
        deldata.setBounds(20, 390, 260, 110);

        updatedata.setBorder(javax.swing.BorderFactory.createTitledBorder("Update data"));
        updatedata.setToolTipText("");
        updatedata.setOpaque(false);
        updatedata.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(updeid);
        updeid.setText("Emp_ID");
        updeid.setOpaque(false);
        updatedata.add(updeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, -1, -1));

        buttonGroup1.add(updname);
        updname.setText("EName");
        updname.setOpaque(false);
        updatedata.add(updname, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 27, -1, -1));

        buttonGroup1.add(updsal);
        updsal.setText("ESalary");
        updsal.setOpaque(false);
        updatedata.add(updsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 27, 84, -1));

        buttonGroup1.add(updjdate);
        updjdate.setText("Join_Date");
        updjdate.setOpaque(false);
        updatedata.add(updjdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 52, -1, -1));

        jLabel7.setText("New Value");
        updatedata.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 107, -1, 31));
        updatedata.add(newval, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 107, 135, -1));

        update.setText("Update");
        update.setFocusPainted(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        updatedata.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 145, -1, -1));

        jLabel8.setText("Enter Emp_ID");
        updatedata.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 83, -1, -1));
        updatedata.add(emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 80, 135, -1));

        jPanel1.add(updatedata);
        updatedata.setBounds(20, 190, 260, 190);

        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next);
        next.setBounds(429, 510, 110, 25);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication6/emp_image.png"))); // NOI18N
        image.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                imageComponentShown(evt);
            }
        });
        jPanel1.add(image);
        image.setBounds(0, 0, 560, 550);
        jPanel1.add(mID);
        mID.setBounds(10, 470, 80, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void imageComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imageComponentShown
        // TODO add your handling code here:
       
       
    }//GEN-LAST:event_imageComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
       
        
       String url="jdbc:mysql://localhost:3306/project?useSSL=true";
       String user="root";
       String pass="harsh";
       
               try{

             Class.forName("com.mysql.cj.jdbc.Driver");
             Connection conn=DriverManager.getConnection(url,user,pass);
             //setting the branch name on top of the page
             String sql = "Select city from branch where manager_id=?";
             PreparedStatement pst = conn.prepareStatement(sql);
             pst.setString(1, mID.getText());
             ResultSet rs = pst.executeQuery();
            
             rs.next();
             String op=rs.getString(1);
            
             
             city.setText(op+" Branch");
        
             //setting table values 
             String sql2="select * from employee where branch_id=(select branch_id from branch where manager_id=?)";
             PreparedStatement pst1=conn.prepareStatement(sql2);
             pst1.setString(1, mID.getText());
             ResultSet rs1=pst1.executeQuery();
             
             DefaultTableModel tm=(DefaultTableModel)employee.getModel();
             tm.setRowCount(0);
              while(rs1.next())
                        {
                           Object o[]={rs1.getInt("Emp_ID"),rs1.getString("EName"),rs1.getInt("ESalary"),rs1.getString("Join_Date"),rs1.getInt("Branch_ID")};
                              tm.addRow(o);
                        }
              
             conn.close();
      }catch(Exception e){System.out.println(e);}
               
               

    }//GEN-LAST:event_formComponentShown

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        int a=Integer.parseInt(eid.getText());
        String b=en.getText();
        int c=Integer.parseInt(esal.getText());
        String d=jdate.getText();
        int e=Integer.parseInt(bid.getText());
        
        String url="jdbc:mysql://localhost:3306/project?useSSL=true";
        String user="root";
        String pass="harsh";

        try{

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection(url,user,pass);
            String sql = "insert into employee values(?,?,?,?,?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1,a);
            pst.setString(2,b);
            pst.setInt(3,c);
            pst.setString(4,d);
            pst.setInt(5,e);
            pst.executeUpdate();
            
      

            JOptionPane.showMessageDialog(null,"New emplooyee added successfuly!");
   
            sleep(5);
            
             String sql2="select * from employee where branch_id=(select branch_id from branch where manager_id=?)";
             PreparedStatement pst1=conn.prepareStatement(sql2);
             pst1.setString(1, mID.getText());
             ResultSet rs1=pst1.executeQuery();
             
             DefaultTableModel tm=(DefaultTableModel)employee.getModel();
             tm.setRowCount(0);
              while(rs1.next())
                        {
                           Object o[]={rs1.getInt("Emp_ID"),rs1.getString("EName"),rs1.getInt("ESalary"),rs1.getString("Join_Date"),rs1.getInt("Branch_ID")};
                              tm.addRow(o);
                        }

            
           

            conn.close();
        }catch(Exception f){System.out.println(f);}
        
         eid.setText("");
         en.setText("");
         esal.setText("");
         jdate.setText("");
         bid.setText("");

       
        
        

    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
          
        
       String url="jdbc:mysql://localhost:3306/project?useSSL=true";
       String user="root";
       String pass="harsh";
       
               try{

             Class.forName("com.mysql.cj.jdbc.Driver");
             Connection conn=DriverManager.getConnection(url,user,pass);
             //deleting data
             String sql = "Delete from employee where emp_id=?";
             PreparedStatement pst = conn.prepareStatement(sql);
             pst.setInt(1, Integer.parseInt(delID.getText()));
              pst.executeUpdate();
            
         
              
               int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete all data related to this employee?",null, JOptionPane.YES_NO_OPTION);
                if(result == JOptionPane.YES_OPTION) 
                {
                         pst.executeUpdate();
                         JOptionPane.showMessageDialog(null,"Employee details deleted successfully!");
                                    } 
           
                   
   
         
        
             //setting table values 
             String sql2="select * from employee where branch_id=(select branch_id from branch where manager_id=?)";
             PreparedStatement pst1=conn.prepareStatement(sql2);
             pst1.setString(1, mID.getText());
             ResultSet rs1=pst1.executeQuery();
             
             DefaultTableModel tm=(DefaultTableModel)employee.getModel();
             tm.setRowCount(0);
              while(rs1.next())
                        {
                           Object o[]={rs1.getInt("Emp_ID"),rs1.getString("EName"),rs1.getInt("ESalary"),rs1.getString("Join_Date"),rs1.getInt("Branch_ID")};
                              tm.addRow(o);
                        }
              
             conn.close();
             delID.setText("");
      }catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
       String url="jdbc:mysql://localhost:3306/project?useSSL=true";
       String user="root";
       String pass="harsh";
       
             
            
         
              
               int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to update data?",null, JOptionPane.YES_NO_OPTION);
                if(result == JOptionPane.YES_OPTION) 
                {
                      
                    try{

                            Class.forName("com.mysql.cj.jdbc.Driver");
                            Connection conn=DriverManager.getConnection(url,user,pass);
                            //updating data
                            if(updeid.isSelected())
                            {
                                
                            int a=Integer.parseInt(emp.getText());
                            int b=Integer.parseInt(newval.getText());
                            String sql = "Update employee set emp_id=? where emp_id=?";
                            PreparedStatement pst = conn.prepareStatement(sql);
                            pst.setInt(1, b);
                            pst.setInt(2, a);
                             pst.executeUpdate();
                                   
                            }
                            else if(updname.isSelected())
                            {
                            int a=Integer.parseInt(emp.getText());
                            String b=newval.getText();
                            String sql = "Update employee set EName=? where emp_id=?";
                            PreparedStatement pst = conn.prepareStatement(sql);
                            pst.setString(1, b);
                            pst.setInt(2, a);
                             pst.executeUpdate();
                            }
                            else if(updsal.isSelected())
                            {
                             int a=Integer.parseInt(emp.getText());
                            int b=Integer.parseInt(newval.getText());
                            String sql = "Update employee set ESalary=? where emp_id=?";
                            PreparedStatement pst = conn.prepareStatement(sql);
                            pst.setInt(1, b);
                            pst.setInt(2, a);
                             pst.executeUpdate();
                            }
                            else if(updjdate.isSelected())
                            {
                            int a=Integer.parseInt(emp.getText());
                            String b=newval.getText();
                            String sql = "Update employee set Join_Date=? where emp_id=?";
                            PreparedStatement pst = conn.prepareStatement(sql);
                            pst.setString(1, b);
                            pst.setInt(2, a);
                             pst.executeUpdate();
                            }
                      
                        
                            JOptionPane.showMessageDialog(null,"Employee detail updated successfully!");



                                        

                            //setting table values 
                            String sql2="select * from employee where branch_id=(select branch_id from branch where manager_id=?)";
                            PreparedStatement pst1=conn.prepareStatement(sql2);
                            pst1.setString(1, mID.getText());
                            ResultSet rs1=pst1.executeQuery();

                            DefaultTableModel tm=(DefaultTableModel)employee.getModel();
                            tm.setRowCount(0);
                             while(rs1.next())
                                       {
                                          Object o[]={rs1.getInt("Emp_ID"),rs1.getString("EName"),rs1.getInt("ESalary"),rs1.getString("Join_Date"),rs1.getInt("Branch_ID")};
                                             tm.addRow(o);
                                       }
                            emp.setText("");
                            newval.setText("");
                            buttonGroup1.clearSelection();
                            conn.close();
                     }catch(Exception e){System.out.println(e);}
               }
    }//GEN-LAST:event_updateActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
              
        
           
             String a=(mID.getText());
             
            
    
            
                dispose();
                new three(a).setVisible(true);
             
        
             
              
      
        
               
          
                
        
    }//GEN-LAST:event_nextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            JOptionPane.showMessageDialog(null, "You have been successfully signed out!");
        dispose();
        new one().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(two.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(two.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(two.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(two.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new two().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JPanel addnew;
    private javax.swing.JTextField bid;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel city;
    private javax.swing.JTextField delID;
    private javax.swing.JPanel deldata;
    private javax.swing.JButton delete;
    private javax.swing.JTextField eid;
    private javax.swing.JTextField emp;
    private javax.swing.JTable employee;
    private javax.swing.JTextField en;
    private javax.swing.JTextField esal;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jdate;
    private javax.swing.JLabel mID;
    private javax.swing.JTextField newval;
    private javax.swing.JButton next;
    private javax.swing.JLabel title;
    private javax.swing.JButton update;
    private javax.swing.JPanel updatedata;
    private javax.swing.JRadioButton updeid;
    private javax.swing.JRadioButton updjdate;
    private javax.swing.JRadioButton updname;
    private javax.swing.JRadioButton updsal;
    // End of variables declaration//GEN-END:variables
}
